# Generated by Django 5.2.1 on 2025-06-03 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escuderia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('any_creacio', models.PositiveIntegerField(help_text="Any de creació de l'escuderia")),
                ('seu', models.CharField(help_text="Seu principal de l'escuderia", max_length=100)),
                ('campionats_pilots', models.PositiveIntegerField(default=0, help_text='Nº de campionats de pilots aconseguits')),
                ('campionats_equips', models.PositiveIntegerField(default=0, help_text='Nº de campionats de constructors aconseguits')),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('edat', models.PositiveIntegerField()),
                ('nacionalitat', models.CharField(max_length=50)),
                ('escuderia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilots', to='f1.escuderia')),
            ],
        ),
        migrations.CreateModel(
            name='Cursa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('pais', models.CharField(help_text='País on es disputa la cursa', max_length=50)),
                ('voltes', models.PositiveIntegerField(help_text='Nº de voltes de la cursa')),
                ('longitud_circuit_km', models.DecimalField(decimal_places=2, help_text='Longitud del circuit en km', max_digits=5)),
                ('pole_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poles', to='f1.pilot')),
            ],
        ),
        migrations.CreateModel(
            name='ResultatCursa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicio_final', models.PositiveIntegerField()),
                ('temps_diferencia', models.DurationField(help_text='Temps respecte al guanyador (HH:MM:SS)')),
                ('cursa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='f1.cursa')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f1.pilot')),
            ],
            options={
                'ordering': ['cursa', 'posicio_final'],
                'unique_together': {('cursa', 'pilot')},
            },
        ),
    ]
